# Generated by Django 5.2.6 on 2025-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('doc', 'Traitement documentaire'), ('game', 'Jeux'), ('web', 'Web'), ('research', 'Recherche'), ('automation', 'Automatisation'), ('training', 'Formation'), ('security', 'Sécurité')], max_length=20)),
                ('tags', models.CharField(blank=True, default='', max_length=300)),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('link_github', models.URLField(blank=True)),
                ('link_demo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
