# Generated by Django 5.2.12 on 2026-03-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('craft_type', models.CharField(choices=[('Alchimie', 'Alchimie'), ('Couture', 'Couture'), ('Cuisine', 'Cuisine'), ('Forge', 'Forge'), ('Ingénierie', 'Ingénierie'), ('Joaillerie', 'Joaillerie'), ('Menuiserie', 'Menuiserie'), ('Tannerie', 'Tannerie'), ('Enchantement', 'Enchantement')], max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('availability', models.CharField(choices=[('Abondant', 'Abondant'), ('Commun', 'Commun'), ('Moyen', 'Moyen'), ('Rare', 'Rare'), ('Légendaire', 'Légendaire')], default='Commun', max_length=20)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('Abondant', 'Abondant'), ('Commun', 'Commun'), ('Moyen', 'Moyen'), ('Rare', 'Rare'), ('Légendaire', 'Légendaire')], default='Commun', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='jdr.city')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='jdr.resource')),
            ],
            options={
                'verbose_name': 'Export de ville',
                'verbose_name_plural': 'Exports de ville',
                'unique_together': {('city', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='MerchantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('buy_price_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('delivered', 'Livré'), ('sold', 'Vendu'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('transit_sessions', models.IntegerField(default=1)),
                ('sessions_remaining', models.IntegerField(default=1)),
                ('created_at_session', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_bought', to='jdr.city')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_orders', to='jdr.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_orders', to='jdr.character')),
                ('sell_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_sold', to='jdr.city')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='jdr.resource')),
            ],
            options={
                'verbose_name': 'Commande marchande',
                'verbose_name_plural': 'Commandes marchandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='jdr.campaign')),
                ('city_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='jdr.cityexport')),
            ],
            options={
                'verbose_name': 'Prix du marché',
                'verbose_name_plural': 'Prix du marché',
                'ordering': ['-session_number'],
                'unique_together': {('city_export', 'campaign', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='MerchantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('average_buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_inventory', to='jdr.character')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='jdr.resource')),
            ],
            options={
                'verbose_name': 'Inventaire marchand',
                'verbose_name_plural': 'Inventaires marchands',
                'unique_together': {('character', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='CityImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='jdr.city')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports_to', to='jdr.city')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='jdr.resource')),
            ],
            options={
                'verbose_name': 'Import de ville',
                'verbose_name_plural': 'Imports de ville',
                'unique_together': {('city', 'resource', 'origin_city')},
            },
        ),
    ]
