# Generated by Django 5.2.12 on 2026-03-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0002_city_resource_cityexport_merchantorder_marketprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemyPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Herbes', 'Herbes'), ('Fleurs', 'Fleurs'), ('Racines', 'Racines'), ('Champignons', 'Champignons'), ('Algues', 'Algues'), ('Résines', 'Résines'), ('Mousses', 'Mousses'), ('Cristaux', 'Cristaux')], max_length=20)),
                ('rarity', models.CharField(choices=[('Commune', 'Commune'), ('Peu commune', 'Peu commune'), ('Rare', 'Rare'), ('Très rare', 'Très rare'), ('Légendaire', 'Légendaire')], max_length=20)),
                ('growth_time', models.IntegerField(help_text="Nombre d'inter-sessions pour pousser")),
                ('yield_amount', models.IntegerField(default=1, help_text='Unités récoltées par plant')),
                ('special_conditions', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icon', models.CharField(default='🌿', max_length=10)),
                ('origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alchemy_plants', to='jdr.city')),
            ],
            options={
                'verbose_name': 'Plante alchimique',
                'verbose_name_plural': 'Plantes alchimiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GardenUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_plots', models.IntegerField(default=4)),
                ('fertilizer_bonus', models.FloatField(default=0, help_text='Réduction du temps de culture en %')),
                ('special_soils', models.JSONField(blank=True, default=list, help_text='Sols spéciaux débloqués')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garden_upgrade', to='jdr.character')),
            ],
            options={
                'verbose_name': 'Amélioration de jardin',
                'verbose_name_plural': 'Améliorations de jardin',
            },
        ),
        migrations.CreateModel(
            name='HarvestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('harvested_at_session', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('sell_price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_logs', to='jdr.character')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_logs', to='jdr.alchemyplant')),
            ],
            options={
                'verbose_name': 'Récolte',
                'verbose_name_plural': 'Récoltes',
                'ordering': ['-harvested_at_session'],
            },
        ),
        migrations.CreateModel(
            name='PlantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('quantity_needed', models.IntegerField(default=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='jdr.alchemyplant')),
            ],
            options={
                'verbose_name': 'Utilisation de plante',
                'verbose_name_plural': 'Utilisations de plantes',
                'ordering': ['recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='GardenPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.IntegerField()),
                ('planted_at_session', models.IntegerField(blank=True, null=True)),
                ('sessions_grown', models.IntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('empty', 'Vide'), ('growing', 'En culture'), ('ready', 'Prête'), ('withered', 'Flétrie')], default='empty', max_length=10)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plots', to='jdr.character')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='jdr.alchemyplant')),
            ],
            options={
                'verbose_name': 'Parcelle de jardin',
                'verbose_name_plural': 'Parcelles de jardin',
                'ordering': ['plot_number'],
                'unique_together': {('character', 'plot_number')},
            },
        ),
    ]
