# Generated by Django 5.2.12 on 2026-03-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0003_alchemyplant_gardenupgrade_harvestlog_plantusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Effet magique de la rune')),
                ('difficulty', models.CharField(choices=[('apprenti', 'Apprenti'), ('adepte', 'Adepte'), ('maître', 'Maître'), ('archimage', 'Archimage')], max_length=20)),
                ('category', models.CharField(choices=[('protection', 'Protection'), ('attaque', 'Attaque'), ('soin', 'Soin'), ('utilité', 'Utilité'), ('invocation', 'Invocation')], max_length=20)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='jdr/runes/templates/')),
                ('mana_cost', models.IntegerField(default=0)),
                ('effect_description', models.TextField(blank=True, default='')),
                ('required_materials', models.JSONField(blank=True, default=dict, help_text='Matériaux nécessaires, ex: {"Encre magique": 1, "Parchemin rare": 1}')),
            ],
            options={
                'verbose_name': 'Modèle de rune',
                'verbose_name_plural': 'Modèles de runes',
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuneDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(help_text='Base64 du canvas PNG')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('mj_feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_drawings', to='jdr.campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_drawings', to='jdr.character')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='jdr.runetemplate')),
            ],
            options={
                'verbose_name': 'Dessin de rune',
                'verbose_name_plural': 'Dessins de runes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuneCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at_session', models.IntegerField()),
                ('uses_remaining', models.IntegerField(blank=True, help_text='None = utilisations illimitées', null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_collection', to='jdr.character')),
                ('rune_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='jdr.runedrawing')),
            ],
            options={
                'verbose_name': 'Rune en collection',
                'verbose_name_plural': 'Runes en collection',
                'ordering': ['-acquired_at_session'],
            },
        ),
    ]
