# Generated by Django 5.2.12 on 2026-03-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0004_runetemplate_runedrawing_runecollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextcloud_path', models.CharField(help_text='Chemin du dossier dans Nextcloud', max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('lore', 'Lore & Histoire'), ('maps', 'Cartes'), ('illustrations', 'Illustrations'), ('music', 'Musiques & Ambiances'), ('rules', 'Règles & Références'), ('notes', 'Notes de session'), ('other', 'Autre')], default='other', max_length=20)),
                ('access_level', models.CharField(choices=[('all_players', 'Tous les joueurs'), ('mj_only', 'MJ uniquement'), ('specific_players', 'Joueurs spécifiques')], default='all_players', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folders', to='jdr.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier partagé',
                'verbose_name_plural': 'Dossiers partagés',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SharedFolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_upload', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='jdr.sharedfolder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folder_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès dossier partagé',
                'verbose_name_plural': 'Accès dossiers partagés',
                'unique_together': {('folder', 'player')},
            },
        ),
    ]
