# Generated by Django 5.2.6 on 2026-03-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0006_alter_character_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rarity', models.CharField(choices=[('commun', 'Commun'), ('peu_commun', 'Peu commun'), ('rare', 'Rare'), ('très_rare', 'Très rare'), ('légendaire', 'Légendaire'), ('artéfact', 'Artéfact')], default='commun', max_length=20)),
                ('item_type', models.CharField(blank=True, default='', help_text='Arme, armure, potion, etc.', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text="Valeur en pièces d'or", max_digits=10)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Propriétés libres (ex: dégâts, bonus)')),
                ('is_magical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Objet',
                'verbose_name_plural': 'Objets',
                'ordering': ['name'],
                'unique_together': {('campaign', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(default=1)),
                ('mana_cost', models.IntegerField(default=0)),
                ('damage', models.CharField(blank=True, default='', max_length=100)),
                ('range_distance', models.CharField(blank=True, default='', max_length=100)),
                ('casting_time', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('school', models.CharField(blank=True, default='', max_length=100)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Champs libres supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Sort',
                'verbose_name_plural': 'Sorts',
                'ordering': ['level', 'name'],
                'unique_together': {('campaign', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['display_order', 'name'],
                'unique_together': {('campaign', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='jdr.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_entries', to='jdr.item')),
            ],
            options={
                'verbose_name': 'Objet de personnage',
                'verbose_name_plural': 'Objets de personnage',
                'unique_together': {('character', 'item')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_spells', to='jdr.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_entries', to='jdr.spell')),
            ],
            options={
                'verbose_name': 'Sort de personnage',
                'verbose_name_plural': 'Sorts de personnage',
                'unique_together': {('character', 'spell')},
            },
        ),
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_stats', to='jdr.character')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_values', to='jdr.stat')),
            ],
            options={
                'verbose_name': 'Statistique de personnage',
                'verbose_name_plural': 'Statistiques de personnage',
                'ordering': ['stat__display_order', 'stat__name'],
                'unique_together': {('character', 'stat')},
            },
        ),
    ]
