# Generated by Django 5.2.6 on 2026-03-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0007_item_spell_stat_characteritem_characterspell_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order', 'Commande marchande'), ('join', 'Nouveau membre'), ('advance', 'Avancement de session'), ('rune_submit', 'Soumission de rune'), ('rune_review', 'Validation de rune'), ('harvest', 'Récolte'), ('character_create', 'Création de personnage'), ('item_give', "Attribution d'objet"), ('spell_learn', 'Apprentissage de sort'), ('other', 'Autre')], max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('link_hash', models.CharField(blank=True, default='', help_text='Hash route pour naviguer vers la page liée', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_events', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Événement de campagne',
                'verbose_name_plural': 'Événements de campagne',
                'ordering': ['-created_at'],
            },
        ),
    ]
