# Generated by Django 5.2.6 on 2026-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0008_campaignevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='jdr.city'),
        ),
    ]
