# Generated by Django 5.2.6 on 2026-03-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0009_campaign_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resource',
            field=models.ForeignKey(blank=True, help_text="Ressource d'origine (si créé via le comptoir)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='jdr.resource'),
        ),
    ]
