# Generated by Django 5.2.6 on 2026-04-05 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0010_item_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='copper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_dice_roll', models.BooleanField(default=False)),
                ('dice_result', models.JSONField(blank=True, help_text='Ex: {"command": "2d20", "rolls": [14, 7], "total": 21}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jdr_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('is_private', models.BooleanField(default=False, help_text='Si True, visible uniquement par le MJ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Note de session',
                'verbose_name_plural': 'Notes de session',
                'ordering': ['-updated_at'],
                'unique_together': {('campaign', 'is_private')},
            },
        ),
    ]
