# Generated by Django 5.2.6 on 2026-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0011_character_copper_character_gold_character_silver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='session_active',
            field=models.BooleanField(default=False),
        ),
    ]
