# Generated by Django 5.2.6 on 2026-04-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0012_campaign_session_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('hp', models.IntegerField(default=10, help_text='Points de vie')),
                ('armor_class', models.IntegerField(default=10, help_text="Classe d'armure")),
                ('attack', models.CharField(blank=True, default='', help_text='Attaque principale (ex: 1d20+5)', max_length=200)),
                ('damage', models.CharField(blank=True, default='', help_text='Dégâts (ex: 2d6+3)', max_length=200)),
                ('special_abilities', models.TextField(blank=True, default='', help_text='Capacités spéciales')),
                ('challenge_rating', models.CharField(blank=True, default='', help_text='Niveau de défi', max_length=20)),
                ('monster_type', models.CharField(blank=True, default='', help_text='Type (bête, mort-vivant, dragon…)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jdr/monsters/')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Stats campagne: {stat_id: value}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Monstre',
                'verbose_name_plural': 'Monstres',
                'ordering': ['name'],
                'unique_together': {('campaign', 'name')},
            },
        ),
    ]
