# Generated by Django 5.2.6 on 2026-04-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0013_monster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_min', models.IntegerField(default=0, help_text='Valeur minimum autorisée par statistique')),
                ('stat_max', models.IntegerField(default=20, help_text='Valeur maximum autorisée par statistique')),
                ('points_per_level', models.IntegerField(default=5, help_text='Nombre de points de statistique attribués par niveau')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Paramètres de campagne',
                'verbose_name_plural': 'Paramètres de campagne',
            },
        ),
    ]
