# Generated by Django 5.2.6 on 2026-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0014_campaignsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='base_points',
            field=models.IntegerField(default=10, help_text='Nombre de points de statistique au niveau 1'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='points_per_level',
            field=models.IntegerField(default=5, help_text='Nombre de points de statistique gagnés par niveau supplémentaire'),
        ),
    ]
