# Generated by Django 5.2.6 on 2026-04-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0015_campaignsettings_base_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='stats',
        ),
    ]
