# Generated by Django 5.2.6 on 2026-04-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0017_skill_characterskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Champs libres supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_skills', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Compétence passive',
                'verbose_name_plural': 'Compétences passives',
                'ordering': ['name'],
                'unique_together': {('campaign', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterPassiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_passive_skills', to='jdr.character')),
                ('passive_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_entries', to='jdr.passiveskill')),
            ],
            options={
                'verbose_name': 'Compétence passive de personnage',
                'verbose_name_plural': 'Compétences passives de personnage',
                'unique_together': {('character', 'passive_skill')},
            },
        ),
    ]
