# Generated by Django 5.2.6 on 2026-04-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0018_add_passiveskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jdr.character')),
                ('armor_class', models.IntegerField(default=10, help_text="Classe d'armure")),
                ('attack', models.CharField(blank=True, default='', help_text='Attaque principale (ex: 1d20+5)', max_length=200)),
                ('damage', models.CharField(blank=True, default='', help_text='Dégâts (ex: 2d6+3)', max_length=200)),
                ('special_abilities', models.TextField(blank=True, default='', help_text='Capacités spéciales')),
                ('challenge_rating', models.CharField(blank=True, default='', help_text='Niveau de défi', max_length=20)),
                ('monster_type', models.CharField(blank=True, default='', help_text='Type (bête, mort-vivant, dragon…)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jdr/monsters/')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Stats campagne: {stat_id: value}')),
            ],
            options={
                'verbose_name': 'Monstre',
                'verbose_name_plural': 'Monstres',
                'ordering': ['name'],
            },
            bases=('jdr.character',),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=0, help_text='Points de vie actuels (gauge0_0)'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=0, help_text='Points de vie max (gauge0_0 base)'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_mp',
            field=models.IntegerField(default=0, help_text='Points de mana max (gauge0_1 base)'),
        ),
        migrations.AddField(
            model_name='character',
            name='mp',
            field=models.IntegerField(default=0, help_text='Points de mana actuels (gauge0_1)'),
        ),
    ]
