# Generated by Django 5.2.6 on 2026-06-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0020_alter_character_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('current_turn_index', models.IntegerField(default=0)),
                ('round_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combat_session', to='jdr.campaign')),
            ],
            options={
                'verbose_name': 'Session de combat',
                'verbose_name_plural': 'Sessions de combat',
            },
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(blank=True, default='', max_length=200)),
                ('initiative', models.IntegerField(default=0, help_text="Valeur d'Agilité pour l'ordre de tour")),
                ('hp_current', models.IntegerField(default=0)),
                ('hp_max', models.IntegerField(default=0)),
                ('is_monster', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0, help_text="Position dans l'ordre de tour (calculé)")),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_participations', to='jdr.character')),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jdr.combatsession')),
            ],
            options={
                'verbose_name': 'Participant au combat',
                'verbose_name_plural': 'Participants au combat',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='CampaignInventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='jdr.campaign')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_entries', to='jdr.item')),
            ],
            options={
                'verbose_name': "Entrée d'inventaire de campagne",
                'verbose_name_plural': "Entrées d'inventaire de campagne",
                'ordering': ['item__name'],
                'unique_together': {('campaign', 'item')},
            },
        ),
    ]
