# Generated by Django 5.2.6 on 2026-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0021_combatsession_combatparticipant_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='characteritem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='character_item_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('resource__isnull', False)), fields=('campaign', 'resource'), name='unique_resource_item_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='merchantinventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='merchant_inventory_quantity_nonnegative'),
        ),
    ]
