# Generated by Django 5.2.6 on 2026-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0022_merchant_inventory_integrity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaigninventoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='campaign_inventory_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='merchantorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='merchant_order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='merchantorder',
            constraint=models.CheckConstraint(condition=models.Q(('transit_sessions__gte', 0)), name='merchant_order_transit_sessions_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='merchantorder',
            constraint=models.CheckConstraint(condition=models.Q(('sessions_remaining__gte', 0)), name='merchant_order_sessions_remaining_nonnegative'),
        ),
    ]
