# Generated by Django 5.2.6 on 2026-07-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0024_separate_monster_creatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimport',
            name='availability',
            field=models.CharField(choices=[('Abondant', 'Abondant'), ('Commun', 'Commun'), ('Moyen', 'Moyen'), ('Rare', 'Rare'), ('Légendaire', 'Légendaire')], default='Commun', help_text='Disponibilité locale de la ressource dans la ville importatrice', max_length=20),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='buy_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_bought', to='jdr.city'),
        ),
    ]
