# Generated by Django 5.2.6 on 2026-07-23 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0025_merchant_economic_logic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplot',
            name='fertilizer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gardenplot',
            name='mutation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gardenplot',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('terreau', 'Terreau'), ('humus', 'Humus'), ('sable', 'Sable'), ('cendres', 'Cendres volcaniques'), ('fertile', 'Terre fertile'), ('sterile', 'Terre stérile')], default='terreau', max_length=20),
        ),
        migrations.AddField(
            model_name='gardenupgrade',
            name='grid_columns',
            field=models.IntegerField(default=4, help_text='Nombre de colonnes de la grille'),
        ),
        migrations.AddField(
            model_name='runedrawing',
            name='mj_annotations',
            field=models.JSONField(blank=True, default=dict, help_text='Annotations MJ sur le dessin (cercles, fleches, textes)'),
        ),
        migrations.CreateModel(
            name='PlantMutationRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.JSONField(default=list, help_text='Matrice 3x3 : null = indifferent, int = plant_id, "category:<nom>" = filtre categorie')),
                ('required_soil', models.CharField(blank=True, default='', max_length=20)),
                ('required_fertilizer', models.CharField(blank=True, default='', max_length=50)),
                ('is_hidden', models.BooleanField(default=True, help_text='Cachee jusqu a decouverte par un joueur')),
                ('discovery_hint', models.TextField(blank=True, default='')),
                ('result_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_recipes', to='jdr.alchemyplant')),
            ],
            options={
                'verbose_name': 'Recette de mutation',
                'verbose_name_plural': 'Recettes de mutation',
            },
        ),
        migrations.CreateModel(
            name='PlotMutationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_value', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=False)),
                ('session', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harvested_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_mutation_logs', to='jdr.alchemyplant')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_logs', to='jdr.gardenplot')),
                ('recipe_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutation_logs', to='jdr.plantmutationrecipe')),
                ('result_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_mutation_logs', to='jdr.alchemyplant')),
            ],
            options={
                'verbose_name': 'Log de mutation',
                'verbose_name_plural': 'Logs de mutation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuneDrawingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], max_length=20)),
                ('image_data', models.TextField(blank=True, default='', help_text='Snapshot base64 optionnel')),
                ('feedback', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jdr.runedrawing')),
            ],
            options={
                'verbose_name': 'Historique de dessin de rune',
                'verbose_name_plural': 'Historiques de dessins de runes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('times_triggered', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_recipes', to='jdr.character')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='jdr.plantmutationrecipe')),
            ],
            options={
                'verbose_name': 'Recette decouverte',
                'verbose_name_plural': 'Recettes decouvertes',
                'ordering': ['-discovered_at'],
                'unique_together': {('character', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='RuneFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_favorites', to='jdr.character')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='jdr.runetemplate')),
            ],
            options={
                'verbose_name': 'Rune favorite',
                'verbose_name_plural': 'Runes favorites',
                'ordering': ['-created_at'],
                'unique_together': {('character', 'template')},
            },
        ),
    ]
