# Generated by Django 5.2.6 on 2026-07-28 17:18

import django.db.models.deletion
import jdr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0027_monster_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfolder',
            name='nextcloud_path',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Jet secret : visible uniquement par le MJ et son auteur'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='whisper_to',
            field=models.ForeignKey(blank=True, help_text='Si défini, message chuchoté du MJ vers ce joueur uniquement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jdr_whispers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jdr.models.shared_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jdr.sharedfolder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier partagé',
                'verbose_name_plural': 'Fichiers partagés',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
