# Generated by Django 5.2.6 on 2026-08-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0028_remove_sharedfolder_nextcloud_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Personnage système (ex. MJ) masqué dans les listes.'),
        ),
    ]
