# Generated by Django 5.2.6 on 2026-08-02 11:47

from django.db import migrations


def create_hidden_mj_characters(apps, schema_editor):
    Campaign = apps.get_model('jdr', 'Campaign')
    Character = apps.get_model('jdr', 'Character')
    for campaign in Campaign.objects.all():
        if not Character.objects.filter(
            campaign=campaign, player=campaign.game_master, name='MJ'
        ).exists():
            Character.objects.create(
                campaign=campaign,
                player=campaign.game_master,
                name='MJ',
                class_type='MJ',
                description='Personnage système du Maître du Jeu',
                level=1,
                is_hidden=True,
            )


def remove_hidden_mj_characters(apps, schema_editor):
    Character = apps.get_model('jdr', 'Character')
    Character.objects.filter(
        name='MJ',
        description='Personnage système du Maître du Jeu',
        is_hidden=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0029_add_character_is_hidden'),
    ]

    operations = [
        migrations.RunPython(create_hidden_mj_characters, remove_hidden_mj_characters),
    ]
