# Generated by Django 5.2.6 on 2026-08-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0030_create_hidden_mj_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenupgrade',
            name='plot_unlock_cost',
            field=models.IntegerField(default=3, help_text='Nombre de plantes nécessaires pour débloquer une parcelle'),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='consumed',
            field=models.BooleanField(default=False, help_text='Consomme pour debloquer une parcelle'),
        ),
        migrations.AlterField(
            model_name='gardenplot',
            name='status',
            field=models.CharField(choices=[('empty', 'Vide'), ('growing', 'En culture'), ('ready', 'Prête'), ('withered', 'Flétrie'), ('locked', 'Verrouillée')], default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='gardenupgrade',
            name='grid_columns',
            field=models.IntegerField(default=5, help_text='Nombre de colonnes de la grille'),
        ),
        migrations.AlterField(
            model_name='gardenupgrade',
            name='max_plots',
            field=models.IntegerField(default=25),
        ),
    ]
