# Generated by Django 5.2.6 on 2026-08-02 17:04

from django.db import migrations


def migrate_to_5x5_grid(apps, schema_editor):
    GardenUpgrade = apps.get_model('jdr', 'GardenUpgrade')
    GardenPlot = apps.get_model('jdr', 'GardenPlot')

    # Update all upgrades to 5x5 defaults
    GardenUpgrade.objects.update(
        max_plots=25,
        grid_columns=5,
        plot_unlock_cost=3,
    )

    # Central and adjacent plot numbers for a 5x5 grid (1-indexed, row-major)
    CENTER = 13
    SIDE_PLOTS = [12, 14, 18]

    # Process character by character to respect unique_together
    for upgrade in GardenUpgrade.objects.select_related('character').iterator():
        character = upgrade.character
        plots = list(GardenPlot.objects.filter(character=character))

        if not plots:
            # No plots yet: create the whole 5x5 grid
            locked = [
                GardenPlot(
                    character=character,
                    plot_number=i,
                    status='empty' if i == CENTER else 'locked',
                )
                for i in range(1, 26)
            ]
            GardenPlot.objects.bulk_create(locked)
            continue

        # Temporarily move existing plots to a unique high number based on id
        # to avoid unique_together collisions while reassigning.
        for plot in plots:
            plot.plot_number = 10000 + plot.id
            plot.save(update_fields=['plot_number'])

        # Choose the best plot to keep as the center: ready/growing first,
        # then by higher sessions_grown, then empty, then first by id.
        def sort_key(plot):
            status_order = {'ready': 0, 'growing': 1, 'empty': 2, 'withered': 3, 'locked': 4}
            return (status_order.get(plot.status, 5), -plot.sessions_grown, plot.id)

        plots.sort(key=sort_key)

        # Center plot keeps its current data
        center_plot = plots[0]
        center_plot.plot_number = CENTER
        center_plot.save(update_fields=['plot_number'])

        # The next 3 become locked around the center; clear plant data
        side_indices = 0
        for plot in plots[1:4]:
            plot.plot_number = SIDE_PLOTS[side_indices]
            side_indices += 1
            plot.plant = None
            plot.planted_at_session = None
            plot.sessions_grown = 0
            plot.is_ready = False
            plot.status = 'locked'
            plot.fertilizer = ''
            plot.mutation_count = 0
            plot.save()

        # Any remaining existing plots (if more than 4) are moved beyond 25 and locked
        for plot in plots[4:]:
            plot.plant = None
            plot.planted_at_session = None
            plot.sessions_grown = 0
            plot.is_ready = False
            plot.status = 'locked'
            plot.fertilizer = ''
            plot.mutation_count = 0
            plot.plot_number = 10000 + plot.id
            plot.save()

        # Create missing plots 1-25, excluding the 4 we just assigned
        existing_numbers = {CENTER} | set(SIDE_PLOTS)
        to_create = [
            GardenPlot(
                character=character,
                plot_number=i,
                status='locked',
            )
            for i in range(1, 26)
            if i not in existing_numbers
        ]
        GardenPlot.objects.bulk_create(to_create)


def reverse_migrate(apps, schema_editor):
    # Reversing is intentionally a no-op; the data change is not safely
    # reversible without user input.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jdr', '0031_gardenupgrade_plot_unlock_cost_harvestlog_consumed_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_5x5_grid, reverse_migrate),
    ]
