# Generated by Django 5.2.6 on 2026-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='metric_type',
            field=models.CharField(choices=[('weight_reps', 'Poids × Répétitions'), ('distance', 'Distance (mètres)'), ('duration', 'Durée (minutes)'), ('reps_only', 'Répétitions seules')], default='weight_reps', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='quantity_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='metric',
            field=models.CharField(choices=[('max_weight', 'Poids max (kg)'), ('max_reps', 'Reps max'), ('total_volume', 'Volume total (kg)'), ('max_distance', 'Distance max (m)'), ('max_duration', 'Durée max (min)'), ('max_reps_only', 'Reps max (sans poids)'), ('total_distance', 'Distance totale (m)'), ('total_duration', 'Durée totale (min)'), ('total_reps_only', 'Reps total (sans poids)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight_kg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
